# Generated by Django 4.1.7 on 2023-05-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_major_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roll',
            field=models.CharField(default='0', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(choices=[('Computer Science', 'CS'), ('Computer Information System', 'CIS'), ('Bussiness Information Technology', 'BIT'), ('Artifical Intelligence', 'AI'), ('Data Science', 'Data Science'), ('CyberSecurity', 'CyberSecurity')], default='Computer Science', max_length=70),
        ),
    ]
