# Generated by Django 4.2.1 on 2023-05-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_roll_alter_user_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(choices=[('Computer Science', 'CS'), ('Computer Information System', 'CIS'), ('Bussiness Information Technology', 'BIT'), ('Artifical Intelligence', 'AI'), ('Data Science', 'Data Science'), ('CyberSecurity', 'CyberSecurity')], max_length=70, null=True),
        ),
    ]
