# Generated by Django 4.2.1 on 2023-05-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_room_media_file_alter_user_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='media_file',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
