# Generated by Django 4.2.1 on 2023-05-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_room_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='media_file',
        ),
    ]
