# Generated by Django 4.2.1 on 2023-06-02 03:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='majors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Computer Science', 'Computer Science'), ('Computer Information System', 'Computer Information System'), ('Business Information Technology', 'Business Information Technology'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Data Science', 'Data Science'), ('CyberSecurity', 'CyberSecurity')], max_length=200, null=True),
        ),
    ]
