# Generated by Django 4.2.1 on 2023-06-02 03:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_topic_is_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='majors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Computer Science', 'CS'), ('Computer Information System', 'CIS'), ('Bussiness Information Technology', 'BIT'), ('Artifical Intelligence', 'AI'), ('Data Science', 'Data Science'), ('CyberSecurity', 'CyberSecurity')], max_length=200, null=True),
        ),
    ]
