# Generated by Django 4.1.7 on 2023-06-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_defaulttopics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
