# Generated by Django 4.1.7 on 2023-06-02 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_topic_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_selected',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
