# Generated by Django 4.1.7 on 2023-06-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_user_topic_usertopic_user_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='topic',
            field=models.ManyToManyField(through='base.UserTopic', to='base.topic'),
        ),
    ]
