# Generated by Django 4.2.1 on 2023-06-03 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_room_media_file'),
        ('base', '0020_alter_user_topic'),
    ]

    operations = [
    ]
