# Generated by Django 4.1.5 on 2023-06-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_room_role_alter_room_last_rated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roll',
            new_name='role',
        ),
    ]
