# Generated by Django 4.1.5 on 2023-06-05 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_rename_roll_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultTopics',
        ),
    ]
