# Generated by Django 4.1.5 on 2023-06-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_remove_user_role_user_isprofessor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Computer Information Systems', 'Computer Information Systems'), ('Bussiness Information Technology', 'Bussiness Information Technology'), ('Artifical Intelligence', 'Artifical Intelligence'), ('Data Science', 'Data Science'), ('CyberSecurity', 'CyberSecurity'), ('Computer Engineering', 'Computer Engineering'), ('Software Engineering', 'Software Engineering')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='topic',
            field=models.ManyToManyField(limit_choices_to={'majors': models.CharField(choices=[('Computer Science', 'Computer Science'), ('Computer Information Systems', 'Computer Information Systems'), ('Bussiness Information Technology', 'Bussiness Information Technology'), ('Artifical Intelligence', 'Artifical Intelligence'), ('Data Science', 'Data Science'), ('CyberSecurity', 'CyberSecurity'), ('Computer Engineering', 'Computer Engineering'), ('Software Engineering', 'Software Engineering')], max_length=70, null=True)}, through='base.UserTopic', to='base.topic'),
        ),
    ]
