# Generated by Django 4.1.5 on 2023-06-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_topic_majors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='role',
        ),
        migrations.AddField(
            model_name='room',
            name='isProfessor',
            field=models.BooleanField(default=False),
        ),
    ]
